name: Cleanup
description: 'Runs all the cleanup tasks to cleanup resources deployed during E2E'
inputs:
  client-id:
    description: "Client ID"
    required: true
  tenant-id:
    description: "Tenant ID"
    required: true
  subscription-id:
    description: "Subscription ID"
    required: true
  # region:
  #   description: "Region to create aks cluster"
  #   required: true
  resource_group:
    description: "Name of the resource group to create the cluster within"
    required: true
  cluster_name:
    description: 'Name of the cluster to be created'
    required: true
  acr_name:
    description: "Name of the acr holding the karpenter image"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.git_ref }}
    - name: az login
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
    - name: az set sub
      shell: bash
      run: az account set --subscription ${{ inputs.subscription-id }}
    - name: delete cluster ${{ inputs.cluster_name }}
      shell: bash
      run: az aks delete --name ${{ inputs.cluster_name }} --resource-group ${{ inputs.resource_group }} --yes --no-wait
    - name: delete acr ${{ inputs.acr_name }}
      shell: bash
      run: az acr delete --name ${{ inputs.acr_name }} --resource-group ${{ inputs.resource_group }} --yes
    - name: delete rg ${{ inputs.resource_group }}
      shell: bash
      run: az group delete --name ${{ inputs.resource_group }} --yes --no-wait
