# Shared AKSNodeClass (common for both Spot and On-Demand)
---
apiVersion: karpenter.azure.com/v1alpha2
kind: AKSNodeClass
metadata:
  name: default
  annotations:
    kubernetes.io/description: "General purpose AKSNodeClass for running Ubuntu nodes"
spec:
  imageFamily: Ubuntu

# On-Demand NodePool (default)
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
  annotations:
    kubernetes.io/description: "General purpose On-Demand NodePool"
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1s
    budgets:
      - nodes: "100%"
  template:
    spec:
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      expireAfter: Never
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.azure.com/sku-name
          operator: In
          values: [Standard_D2s_v4]

# Spot NodePool
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot
  annotations:
    kubernetes.io/description: "Spot NodePool for burstable cost-efficient workloads"
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1s
    budgets:
      - nodes: "100%"
  template:
    spec:
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      expireAfter: Never
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.azure.com/sku-name
          operator: In
          values: [Standard_D2s_v4]
