defaultBaseImage: mcr.microsoft.com/azurelinux/distroless/base:3.0@sha256:3dcd23ead3035173915ddf670ea28d48cdcb6208025c8f31ce66e185053e8444
defaultPlatforms:
  - linux/arm64
  - linux/amd64
defaultEnv:
  - CGO_ENABLED=1
