defaultBaseImage: mcr.microsoft.com/azurelinux/distroless/base:3.0@sha256:f8f5a9bb739ad1ec347853144c9ed4ca2260e587082277bc6066fcd5cc9973e8
defaultPlatforms:
  - linux/arm64
  - linux/amd64
defaultEnv:
  - CGO_ENABLED=1
