{
  "branches": ["main", "charliedmcb/test-release-branch"],
  "dryRun": true,
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "conventionalcommits"
      }
    ],
    [
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits"
      }
    ],
    [
      "@semantic-release/github",
      {
        "successComment": false,
        "failComment": false,
        "failTitle": false,
        "labels": false,
        "releasedLabels": false
      }
    ]
  ]
}