{
  "branches": ["main", "charliedmcb/test-release-branch"],
  "dryRun": true,
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "conventionalcommits",
        "presetConfig": {
          "header": "Changelog",
          "types": [
            {"type": "feat", "section": "Features"},
            {"type": "fix", "section": "Bug Fixes"},
            {"type": "chore", "hidden": true},
            {"type": "docs", "hidden": true},
            {"type": "style", "hidden": true},
            {"type": "refactor", "hidden": true},
            {"type": "perf", "hidden": true},
            {"type": "test", "hidden": true}
          ],
          "preMajor": true
        }
      }
    ],
    [
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits",
        "presetConfig": {
          "header": "Changelog",
          "types": [
            {"type": "feat", "section": "Features"},
            {"type": "fix", "section": "Bug Fixes"},
            {"type": "chore", "hidden": true},
            {"type": "docs", "hidden": true},
            {"type": "style", "hidden": true},
            {"type": "refactor", "hidden": true},
            {"type": "perf", "hidden": true},
            {"type": "test", "hidden": true}
          ],
          "preMajor": true
        }
      }
    ],
    [
      "@semantic-release/github",
      {
        "successComment": false,
        "failComment": false,
        "failTitle": false,
        "labels": false,
        "releasedLabels": false
      }
    ]
  ]
}