apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: controller
      ko:
        main: github.com/Azure/karpenter-provider-azure/cmd/controller
        dependencies:
          paths:
            - '**/*.go'
            - '**/*.gtpl'
            #flags: ['-tags', 'ccp']
manifests:
  helm:
    releases:
      - name: karpenter
        chartPath: charts/karpenter
        skipBuildDependencies: true
        namespace: kube-system
        createNamespace: true
        setValueTemplates:
          controller.image.repository: "{{.IMAGE_REPO_controller}}"
          controller.image.tag: "{{.IMAGE_TAG_controller}}"
          controller.image.digest: "{{.IMAGE_DIGEST_controller}}"
        valuesFiles:
          - karpenter-values.yaml
          - skaffold-overrides.yaml
deploy:
  helm: {}
