/*
Portions Copyright (c) Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package validation defines the authoritative set of AKS validation rules
// for labels and taints that Karpenter CRD CEL rules must enforce.
//
// These rules mirror AKS RP validation (utils_agentpool.go, nodetaintsvalidator.go,
// k8slabels package). When RP validation changes, this file must be updated, and
// the CEL generation pipeline will propagate the change to CRDs.
//
// Keeping this as the single source of truth eliminates manual duplication between
// Karpenter CRD CEL rules and RP Go validation code.
package validation

// AKSLabelDomain is the label domain reserved by AKS.
// Users cannot set labels under this domain unless they are in the allowlist.
// Mirrors: aks-rp toolkit/constvalues/k8slabels.AKSPrefixValue
const AKSLabelDomain = "kubernetes.azure.com"

// AllowedAKSUserLabels are the kubernetes.azure.com/* label keys that users
// ARE allowed to set on NodePool labels/requirements. All other keys under
// the kubernetes.azure.com/ prefix are blocked.
//
// This list must stay in sync with aks-rp isWhiteListAKSLabels() in
// validation/utils/utils_agentpool.go.
//
// Note: Karpenter well-known labels (e.g., sku-cpu, sku-memory) are also
// included because they are used for scheduling simulation and may appear
// in NodePool labels/requirements.
var AllowedAKSUserLabels = []string{
	// Spot priority — allowed when value matches the pool's spot config
	AKSLabelDomain + "/scalesetpriority",

	// Networking labels — allowed when values match the pool's VNet config
	AKSLabelDomain + "/network-name",
	AKSLabelDomain + "/network-subnet",
	AKSLabelDomain + "/network-subscription",
	AKSLabelDomain + "/network-resourcegroup",
	AKSLabelDomain + "/nodenetwork-vnetguid",

	// Pod networking labels — allowed when values match the pool's pod subnet config
	AKSLabelDomain + "/podnetwork-subscription",
	AKSLabelDomain + "/podnetwork-resourcegroup",
	AKSLabelDomain + "/podnetwork-name",
	AKSLabelDomain + "/podnetwork-subnet",
	AKSLabelDomain + "/podnetwork-delegationguid",

	// Karpenter well-known labels used for scheduling simulation.
	// These are generated by Karpenter and used in requirements/labels for scheduling.
	AKSLabelDomain + "/sku-cpu",
	AKSLabelDomain + "/sku-memory",
	AKSLabelDomain + "/cluster",
	AKSLabelDomain + "/mode",
	AKSLabelDomain + "/os-sku",
	AKSLabelDomain + "/fips_enabled",
}

// AllowedAKSUserTaintKeys are the kubernetes.azure.com/* taint keys that users
// ARE allowed to set on NodePool taints/startupTaints. All other keys under
// the kubernetes.azure.com/ prefix are blocked.
//
// This list must stay in sync with aks-rp isTaintAnAllowedAKSSystemTaint() in
// validation/nodetaints/nodetaintsvalidator.go.
var AllowedAKSUserTaintKeys = []string{
	// Spot pool taint — added automatically for spot pools, also allowed for user to set
	AKSLabelDomain + "/scalesetpriority",

	// Gateway mode taint
	AKSLabelDomain + "/mode",

	// Hosted VM taint for hobo (HostedSystem) pools
	AKSLabelDomain + "/hostedvm",
}

// BlockedK8sSystemLabelKeys are Kubernetes system label keys that users cannot set.
// These are set by kubelet/AgentBaker and must not be overridden.
//
// This list must stay in sync with aks-rp GetK8sSystemLabelKeys() in
// toolkit/constvalues/k8slabels/labels.go.
var BlockedK8sSystemLabelKeys = []string{
	"beta.kubernetes.io/arch",
	"beta.kubernetes.io/instance-type",
	"beta.kubernetes.io/os",
	"failure-domain.beta.kubernetes.io/region",
	"failure-domain.beta.kubernetes.io/zone",
	"failure-domain.kubernetes.io/zone",
	"failure-domain.kubernetes.io/region",
	"kubernetes.io/arch",
	"kubernetes.io/hostname",
	"kubernetes.io/os",
	"kubernetes.io/instance-type",
	"node.kubernetes.io/instance-type",
	"topology.kubernetes.io/region",
	"topology.kubernetes.io/zone",
}

// BlockedAgentBakerLabelKeys are non-prefixed label keys generated by AgentBaker
// that users cannot set.
//
// This list must stay in sync with aks-rp GetAgentBakerGeneratedLabelKeys() in
// toolkit/constvalues/k8slabels/labels.go.
var BlockedAgentBakerLabelKeys = []string{
	"agentpool",
	"storageprofile",
	"storagetier",
	"accelerator",
}
