name: InstallDependencies
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  k8sVersion:
    description: Kubernetes version to use when installing the toolchain
    default: "1.31.x"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      id: setup-go
      with:
        go-version-file: go.mod
        check-latest: true
        cache-dependency-path: "**/go.sum"
    # Root path permission workaround for caching https://github.com/actions/cache/issues/845#issuecomment-1252594999
    - run: sudo chown "$USER" /usr/local
      shell: bash
    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      id: cache-toolchain
      with:
        path: |
          /usr/local/kubebuilder/bin
          ~/go/bin
        key: ${{ runner.os }}-${{ inputs.k8sVersion }}-toolchain-cache-${{ hashFiles('hack/toolchain.sh') }}
    - if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
      shell: bash
      env:
        K8S_VERSION: ${{ inputs.k8sVersion }}
      run: make toolchain
