/*
Portions Copyright (c) Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgentPoolWindowsProfile agent pool windows profile
//
// swagger:model AgentPoolWindowsProfile
type AgentPoolWindowsProfile struct {

	// containerd package
	ContainerdPackage *string `json:"containerdPackage,omitempty"`

	// disable outbound nat
	DisableOutboundNat *bool `json:"disableOutboundNat,omitempty"`

	// enable next gen networking
	EnableNextGenNetworking *bool `json:"enableNextGenNetworking,omitempty"`
}

// Validate validates this agent pool windows profile
func (m *AgentPoolWindowsProfile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent pool windows profile based on context it is used
func (m *AgentPoolWindowsProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgentPoolWindowsProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentPoolWindowsProfile) UnmarshalBinary(b []byte) error {
	var res AgentPoolWindowsProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
