// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgentPoolSecurityProfile agent pool security profile
//
// swagger:model AgentPoolSecurityProfile
type AgentPoolSecurityProfile struct {

	// enable secure boot
	EnableSecureBoot *bool `json:"enableSecureBoot,omitempty"`

	// enable v t p m
	EnableVTPM *bool `json:"enableVTPM,omitempty"`

	// ssh access
	SSHAccess *int32 `json:"sshAccess,omitempty"`
}

// Validate validates this agent pool security profile
func (m *AgentPoolSecurityProfile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent pool security profile based on context it is used
func (m *AgentPoolSecurityProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgentPoolSecurityProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentPoolSecurityProfile) UnmarshalBinary(b []byte) error {
	var res AgentPoolSecurityProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
