// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArtifactStreamingProfile artifact streaming profile
//
// swagger:model ArtifactStreamingProfile
type ArtifactStreamingProfile struct {

	// enabled
	Enabled *bool `json:"enabled,omitempty"`
}

// Validate validates this artifact streaming profile
func (m *ArtifactStreamingProfile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this artifact streaming profile based on context it is used
func (m *ArtifactStreamingProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArtifactStreamingProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArtifactStreamingProfile) UnmarshalBinary(b []byte) error {
	var res ArtifactStreamingProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
