// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GPUProfile g p u profile
//
// swagger:model GPUProfile
type GPUProfile struct {

	// driver type
	DriverType *int32 `json:"driverType,omitempty"`

	// install g p u driver
	InstallGPUDriver *bool `json:"installGPUDriver,omitempty"`
}

// Validate validates this g p u profile
func (m *GPUProfile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this g p u profile based on context it is used
func (m *GPUProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GPUProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GPUProfile) UnmarshalBinary(b []byte) error {
	var res GPUProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
