name: Bug Report
description: Report a bug in AKS Karpenter provider
labels: bug
body:
  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        https://github.com/Azure/karpenter-provider-azure/releases
      value: |
        <!-- helm ls -A --all -o json | jq '.[] | select(.name=="karpenter") | .app_version' -r -->
        __Karpenter Version:__ v0.0.0
        <!-- kubectl version | grep Server -->
        __Kubernetes Version:__ v1.0.0
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        Briefly describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: |
        Briefly describe what is actually happening
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Problem
      description: |
        How can a maintainer reproduce this issue (be detailed)?
    validations:
      required: true

  - type: textarea
    id: specs-logs
    attributes:
      label: Resource Specs and Logs
      description: |
        Include Provisioner spec(s), pod spec(s), and Karpenter controller logs when you experienced the bug

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true

  - type: textarea
    id: community-note
    attributes:
      label: Community Note
      description: |
        Please keep this note for the community
      value: |
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment
    validations:
      required: true
