server:
  fullnameOverride: prometheus-server
  persistentVolume:
    enabled: false
  nodeSelector:
    kubernetes.azure.com/mode: system

alertmanager:
  persistentVolume:
    enabled: false

kube-state-metrics:
  enabled: false
prometheus-pushgateway:
  enabled: false
prometheus-node-exporter:
  enabled: false

extraScrapeConfigs: |
    - job_name: karpenter
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - karpenter # Does this need to be updated?
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_endpoints_name
        - __meta_kubernetes_endpoint_port_name
        action: keep
        regex: karpenter;http-metrics