name: CreateCluster
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  # k8s_version:
  #   description: 'Version of Kubernetes to use for the launched cluster'
  #   required: false
  #   default: "1.27"
  client-id:
    description:
    required: true
  tenant-id:
    description:
    required: true
  subscription-id:
    description:
    required: true
  resource_group:
    description: "Name of the resource group to create the cluster within"
    required: true
  cluster_name:
    description: 'Name of the cluster to be created'
    required: true
  acr_name:
    description: "Name of the acr holding the karpenter image"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out"
    required: false
  location:
    description: "The azure location to run the e2e test in"
    default: "eastus"
  provisionmode:
    description: "The karpenter provisioning mode to run the e2e test in"
    default: "aksscriptless"
  identity_type:
    description: "The type of managed identity for the cluster (SystemAssigned or UserAssigned)"
    required: false
    default: "SystemAssigned"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ inputs.git_ref }}
    - name: az login
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
    - name: az set sub
      shell: bash
      run: az account set --subscription ${{ inputs.subscription-id }}
    - name: create workload msi
      shell: bash
      env:
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
        AZURE_LOCATION: ${{ inputs.location }}
      run: make az-create-workload-msi
    - name: create cluster
      shell: bash
      env:
        AZURE_CLUSTER_NAME: ${{ inputs.cluster_name }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
        AZURE_ACR_NAME: ${{ inputs.acr_name }}
        AZURE_LOCATION: ${{ inputs.location }}
      run: |
        if [ "${{ inputs.identity_type }}" = "UserAssigned" ]; then
          echo "Creating cluster with user-assigned managed identity"
          make az-mkaks-cilium-userassigned
        else
          echo "Creating cluster with system-assigned managed identity"
          make az-mkaks-cilium
        fi
    - name: az login 2
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
    - name: create federated cred
      shell: bash
      env:
        AZURE_CLUSTER_NAME: ${{ inputs.cluster_name }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
      run: make az-create-federated-cred
    - name: update azure perms
      shell: bash
      env:
        AZURE_CLUSTER_NAME: ${{ inputs.cluster_name }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
        AZURE_LOCATION: ${{ inputs.location }}
        AZURE_ACR_NAME: ${{ inputs.acr_name }}
      run: |
        if [ "${{ inputs.provisionmode }}" = "aksmachineapi" ]; then
          make az-perm-aksmachine
        else
          make az-perm
        fi
        make az-perm-acr
