name: CreateCluster
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  k8s_version:
    description: "Version of Kubernetes to use for the launched cluster (e.g., 1.30). If empty, uses AKS default."
    required: false
  client-id:
    description: "ID of the client to create the cluster with"
    required: true
  tenant-id:
    description: "ID of the tenant to create the cluster in"
    required: true
  subscription-id:
    description: "ID of the subscription to create the cluster in"
    required: true
  resource_group:
    description: "Name of the resource group to create the cluster within"
    required: true
  cluster_name:
    description: "Name of the cluster to be created"
    required: true
  acr_name:
    description: "Name of the acr holding the Karpenter image"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out"
    required: false
  location:
    description: "The azure location to run the e2e test in"
    default: "eastus"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: ${{ inputs.git_ref }}
    - name: az login
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
    - name: az set sub
      shell: bash
      env:
        SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
      run: az account set --subscription "$SUBSCRIPTION_ID"
    - name: create workload msi
      shell: bash
      env:
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
        AZURE_LOCATION: ${{ inputs.location }}
      run: make az-create-workload-msi
    - name: create cluster
      shell: bash
      env:
        AZURE_CLUSTER_NAME: ${{ inputs.cluster_name }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
        AZURE_ACR_NAME: ${{ inputs.acr_name }}
        AZURE_LOCATION: ${{ inputs.location }}
        # Must be amd64 SKU - E2E builds only amd64 images (see KO_DEFAULTPLATFORMS in e2e.yaml)
        AZURE_VM_SIZE: Standard_D4ds_v5 # We have more quota for this VM size so force it to avoid quota errors
        K8S_VERSION: ${{ inputs.k8s_version }}
      run: make az-mkaks-cilium
    - name: az login 2
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
    - name: create federated cred
      shell: bash
      env:
        AZURE_CLUSTER_NAME: ${{ inputs.cluster_name }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
      run: make az-create-federated-cred
    - name: update azure perms
      shell: bash
      env:
        AZURE_CLUSTER_NAME: ${{ inputs.cluster_name }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
        AZURE_LOCATION: ${{ inputs.location }}
        AZURE_ACR_NAME: ${{ inputs.acr_name }}
      run: |
        make az-perm
        make az-perm-acr
