name: CreateCluster
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  # k8s_version:
  #   description: 'Version of Kubernetes to use for the launched cluster'
  #   required: false
  #   default: "1.27"
  client-id:
    description:
    required: true
  tenant-id:
    description:
    required: true
  subscription-id:
    description:
    required: true
  resource_group:
    description: "Name of the resource group to create the cluster within"
    required: true
  cluster_name:
    description: 'Name of the cluster to be created'
    required: true
  acr_name:
    description: "Name of the acr holding the karpenter image"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out"
    required: false
  location:
    description: "The azure location to run the e2e test in"
    default: "westus2"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.git_ref }}
    # - name: az login
    #   uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
    #   with:
    #     client-id: ${{ inputs.client-id }}
    #     tenant-id: ${{ inputs.tenant-id }}
    #     subscription-id: ${{ inputs.subscription-id }}
    - name: az set sub
      shell: bash
      run: az account set --subscription ${{ inputs.subscription-id }}
    - name: create workload msi
      shell: bash
      env:
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
        AZURE_LOCATION: ${{ inputs.location }}
      run: make az-create-workload-msi
    - name: create cluster
      shell: bash
      env:
        AZURE_CLUSTER_NAME: ${{ inputs.cluster_name }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
        AZURE_ACR_NAME: ${{ inputs.acr_name }}
        AZURE_LOCATION: ${{ inputs.location }}
      run: make az-mkaks-cilium
    # - name: az login 2
    #   uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
    #   with:
    #     client-id: ${{ inputs.client-id }}
    #     tenant-id: ${{ inputs.tenant-id }}
    #     subscription-id: ${{ inputs.subscription-id }}
    - name: create federated cred
      shell: bash
      env:
        AZURE_CLUSTER_NAME: ${{ inputs.cluster_name }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
      run: make az-create-federated-cred
    - name: update azure perms
      shell: bash
      env:
        AZURE_CLUSTER_NAME: ${{ inputs.cluster_name }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource_group }}
        AZURE_LOCATION: ${{ inputs.location }}
        AZURE_ACR_NAME: ${{ inputs.acr_name }}
      run: |
        make az-perm
        make az-perm-acr
        make az-perm-aksmachine
