name: InstallKarpenter
description: 'Installs Karpenter on the aks cluster'
inputs:
  client-id:
    description: 
    required: true
  tenant-id:
    description: 
    required: true
  subscription-id:
    description: 
    required: true
  # region:
  #   description: "Region to create aks cluster"
  #   required: true
  resource_group:
    description: "Name of the resource group to create the cluster within"
    required: true
  cluster_name:
    description: 'Name of the cluster to be created'
    required: true
  acr_name:
    description: "Name of the acr holding the karpenter image"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out"
    required: false
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      ref: ${{ inputs.git_ref }}
  - name: az login
    uses: azure/login@v1
    with:
      client-id: ${{ inputs.client-id }}
      tenant-id: ${{ inputs.tenant-id }}
      subscription-id: ${{ inputs.subscription-id }}
  - name: az set sub
    shell: bash
    run: az account set --subscription ${{ inputs.subscription-id }}
  - name: patch skaffold and cilium
    shell: bash
    run: AZURE_CLUSTER_NAME=${{ inputs.cluster_name }} AZURE_RESOURCE_GROUP=${{ inputs.resource_group }} make az-patch-skaffold-azureoverlay
  - name: deploy karpenter to cluster
    shell: bash
    run: AZURE_ACR_NAME=${{ inputs.acr_name }} make az-run
  - name: wait for pods to settle
    shell: bash
    run: |
      ${GITHUB_WORKSPACE}/.github/actions/e2e/install-karpenter/waitforgatekeeper.sh
      sleep 10
  - name: taint nodes as karpenter-system
    shell: bash
    run: |
      kubectl taint nodes CriticalAddonsOnly=true:NoSchedule --all
