name: InstallKarpenter
description: 'Installs Karpenter on the aks cluster'
inputs:
  client-id:
    description: "ID of the client to install Karpenter with"
    required: true
  tenant-id:
    description: "ID of the tenant containing the cluster to install Karpenter into"
    required: true
  subscription-id:
    description: "ID of the subscription containing the cluster to install Karpenter into"
    required: true
  # region:
  #   description: "Region to create aks cluster"
  #   required: true
  resource_group:
    description: "Name of the resource group containing the cluster to install Karpenter into"
    required: true
  cluster_name:
    description: "Name of the cluster to install Karpenter into."
    required: true
  acr_name:
    description: "Name of the acr holding the Karpenter image"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out"
    required: false
  location:
    description: "the azure location to run the e2e test in"
    default: "eastus"
  provisionmode:
    description: "the Karpenter provisioning mode to run the e2e test in"
    default: "aksscriptless"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    with:
      ref: ${{ inputs.git_ref }}
  - name: az login
    uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
    with:
      client-id: ${{ inputs.client-id }}
      tenant-id: ${{ inputs.tenant-id }}
      subscription-id: ${{ inputs.subscription-id }}
  - name: az set sub
    shell: bash
    env:
      SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
    run: az account set --subscription $SUBSCRIPTION_ID
  - name: configure Helm chart values
    shell: bash
    env:
      RESOURCE_GROUP: ${{ inputs.resource_group }}
      CLUSTER_NAME: ${{ inputs.cluster_name }}
      LOCATION: ${{ inputs.location }}
      PROVISION_MODE: ${{ inputs.provisionmode }}
    run: AZURE_CLUSTER_NAME=$CLUSTER_NAME AZURE_RESOURCE_GROUP=$RESOURCE_GROUP AZURE_LOCATION=$LOCATION PROVISION_MODE=$PROVISION_MODE make az-configure-values
  - name: deploy karpenter to cluster
    shell: bash
    env:
      ACR_NAME: ${{ inputs.acr_name }}
    run: AZURE_ACR_NAME=$ACR_NAME make az-run
  - name: taint nodes as karpenter-system
    shell: bash
    run: |
      kubectl taint nodes CriticalAddonsOnly=true:NoSchedule --all
