name: DumpLogs
description: 'Dump logs and debug information from the cluster after a test run'
inputs:
  client-id:
    description: "Client ID"
    required: true
  tenant-id:
    description: "Tenant ID"
    required: true
  subscription-id:
    description: "Subscription ID"
    required: true
  resource_group:
    description: "Name of the resource group for the cluster"
    required: true
  cluster_name:
    description: 'Name of the cluster'
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out"
    required: false
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    with:
      ref: ${{ inputs.git_ref }}
  - name: az login
    uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
    with:
      client-id: ${{ inputs.client-id }}
      tenant-id: ${{ inputs.tenant-id }}
      subscription-id: ${{ inputs.subscription-id }}
  - name: update cluster context
    shell: bash
    run: |
      az aks get-credentials --name ${{ inputs.cluster_name }} --resource-group ${{ inputs.resource_group }}
  - name: controller-logs
    shell: bash
    run: |
      kubectl logs -n kube-system -l app.kubernetes.io/name=karpenter --all-containers --ignore-errors
  - name: describe-karpenter-pods
    shell: bash
    run: |
      kubectl describe pods -n kube-system -l app.kubernetes.io/name=karpenter
  - name: describe-nodes
    shell: bash
    run: |
      kubectl describe nodes
  - name: get-karpenter-events
    shell: bash
    run: |
      kubectl get events -A --field-selector source=karpenter
