[build]
base = "website/"
publish = "public"
command = "npm install; hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.121.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm install; hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.121.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm install; hugo --gc --minify --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.121.1"

[context.branch-deploy]
command = "npm install; hugo --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.121.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
