# This Github action builds and publishes image to Azure Container Registry (ACR),
# from where it is automatically propagated to Microsoft Container Registry (MCR).

name: Build and publish to MCR
on:
  push:
    # Only release on supported semantic version tagging e.g. v0.0.1-rc.0
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+' # Patch to an old version (when we can't use v[0-9]+.[0-9]+.[0-9]+ due to next patch release already existing)
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-test.[a-z0-9]+'

permissions:
  contents: read

jobs:
  publish-images:
    permissions:
      contents: read
      id-token: write # This is required for requesting the JWT
    runs-on:
      labels: [self-hosted, "1ES.Pool=${{ vars.RELEASE_1ES_POOL }}"]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0

    - uses: ./.github/actions/install-deps

    - name: Build and publish image
      env:
        RELEASE_ACR: ${{ secrets.AZURE_REGISTRY }}
      run: |
        az login --identity
        ko version
        ./hack/release/release.sh
