name: E2EMatrixTriggerNap
on:
  workflow_dispatch:
    inputs:
      location:
        type: string
        description: "the azure location to run the e2e test in"
        default: "eastus"
  push:
    branches: [main, "bsoghigian/running-nap"]
  workflow_run:
    workflows: [ApprovalComment]
    types: [completed]

permissions:
  contents: read

jobs:
  resolve:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/resolve-args.yaml
  e2e-matrix:
    permissions:
      contents: read
      id-token: write # This is required for requesting the JWT
      statuses: write # ./.github/actions/commit-status/*          
    needs: [resolve]
    uses: ./.github/workflows/e2e-matrix-nap.yaml
    with:
      git_ref: ${{ needs.resolve.outputs.GIT_REF }}
      location: ${{ inputs.location || 'eastus' }}
    secrets:
      E2E_CLIENT_ID: ${{ secrets.E2E_CLIENT_ID }}
      E2E_TENANT_ID: ${{ secrets.E2E_TENANT_ID }}
      E2E_SUBSCRIPTION_ID: ${{ secrets.E2E_SUBSCRIPTION_ID }}
